Repository jeonhaekang/teamver, pull requests merged in 2023-09, with the labels that each got.

#25 fix : 프로필 수정 페이지 헤더 추가, 프사 변경 버튼 영역 줄이기
  src/pages/profile/[userId]/edit/edit.styles.ts
  src/pages/profile/[userId]/edit/index.page.tsx
Labels: Fix

#27 Feat: 참여 모드 설정 페이지 완료
  src/assets/icons/index.ts
  src/assets/icons/setOff.svg
  src/assets/icons/setOn.svg
  src/components/Commons/Dialogs/Toast/Toast.styles.ts
  src/constants/routes.ts
  src/pages/setting/index.page.tsx
  src/pages/setting/role/index.page.tsx
  src/pages/setting/role/role.hooks.ts
  src/pages/setting/setting.styles.ts
  src/pages/setting/setting.types.ts
  src/states/server/chat/apis.ts
  src/states/server/profile/apis.ts
  src/states/server/profile/mutations.ts
Labels: Feat, Design

#28 Refactor: 캘린더 중복 코드 수정
  src/pages/project/create/index.page.tsx
Labels: Fix, Refactor

#31 fix : 프로필 수정
  src/assets/icons/frame.svg
  src/pages/profile/edit/edit.hooks.ts
  src/pages/profile/edit/edit.styles.ts
  src/pages/profile/edit/index.page.tsx
Labels: Fix, Refactor

#35 Refactor : like
  src/components/Like/LikeCardMember/LikeCardMember.hooks.ts
  src/components/Like/LikeCardMember/LikeCardMember.tsx
  src/components/Like/LikeCardOwner/LikeCardOwner.hooks.ts
  src/components/Like/LikeCardOwner/LikeCardOwner.tsx
  src/components/MyPage/ProjectCard/ProjectCard.styles.ts
  src/components/MyPage/ProjectCard/ProjectCard.tsx
  src/components/MyPage/ProjectCard/ProjectCard.types.ts
  src/components/MyPage/ProjectCard/index.ts
  src/components/MyPage/index.ts
  src/pages/profile/edit/index.page.tsx
Labels: Refactor

#36 Design: profile detail css 수정
  src/components/Commons/ProfileDetail/ProfileDetail.styles.ts
  src/components/Commons/ProfileDetail/ProfileDetail.tsx
Labels: Design

#37 Fix: 프로필(참가자) 오류 수정
  src/components/Home/Home.styles.ts
  src/components/Profile/Member/Member.tsx
  src/components/Profile/Owner/Owner.tsx
Labels: Fix

#40 Refactor: 프로젝트 생성 버튼 수정
  src/components/Commons/ProfileDetail/ProfileDetail.tsx
  src/components/Profile/Owner/Owner.tsx
  src/components/Profile/Profile.styles.ts
  src/styles/mixins/container/container.ts
Labels: Refactor, Design

#43 Refactor : like페이지 폴더 및 파일구조 리팩토링
  src/components/Like/LikeCardMember/index.ts
  src/components/Like/LikeCardOwner/index.ts
  src/pages/like/components/Like/Like.styles.ts
  src/pages/like/components/Like/Member/LikeMemberCard/LikeMemberCard.hooks.ts
  src/pages/like/components/Like/Member/LikeMemberCard/LikeMemberCard.tsx
  src/pages/like/components/Like/Member/LikeMemberCard/LikeMemberCard.types.ts
  src/pages/like/components/Like/Member/LikeMemberCard/index.ts
  src/pages/like/components/Like/Member/Member.tsx
  src/pages/like/components/Like/Member/index.ts
  src/pages/like/components/Like/Owner/LikeOwnerCard/LikeOwnerCard.hooks.ts
  src/pages/like/components/Like/Owner/LikeOwnerCard/LikeOwnerCard.tsx
  src/pages/like/components/Like/Owner/LikeOwnerCard/LikeOwnerCard.types.ts
  src/pages/like/components/Like/Owner/LikeOwnerCard/index.ts
  src/pages/like/components/Like/Owner/Owner.tsx
  src/pages/like/components/Like/Owner/index.ts
  src/pages/like/components/Like/index.ts
  src/pages/like/index.page.tsx
Labels: Refactor

#46 Refactor : 찜 페이지
  src/pages/like/components/Member/LikeMemberCard/LikeMemberCard.hooks.ts
  src/pages/like/components/Owner/LikeOwnerCard/LikeOwnerCard.hooks.ts
Labels: Refactor

#49 Refactor/project
  src/pages/project/Project.styles.ts
  src/pages/project/create/create.hooks.ts
  src/pages/project/create/create.styles.ts
  src/pages/project/create/create.types.ts
  src/pages/project/create/index.page.tsx
  src/pages/project/edit/edit.hooks.ts
  src/pages/project/edit/edit.types.ts
  src/pages/project/edit/index.page.tsx
  src/pages/project/members/Member/Member.constant.ts
  src/pages/project/members/Member/Member.hooks.tsx
  src/pages/project/members/Member/Member.tsx
  src/pages/project/members/Member/index.ts
  src/pages/project/members/Owner/Owner.constants.ts
  src/pages/project/members/Owner/Owner.tsx
  src/pages/project/members/Owner/index.ts
  src/pages/project/members/components/ProjectMemberList/ProjectMemberList.constants.ts
  src/pages/project/members/components/ProjectMemberList/ProjectMemberList.hooks.ts
  src/pages/project/members/components/ProjectMemberList/ProjectMemberList.styles.ts
  src/pages/project/members/components/ProjectMemberList/ProjectMemberList.tsx
  src/pages/project/members/components/ProjectMemberList/index.ts
  src/pages/project/members/components/index.ts
  src/pages/project/members/index.page.tsx
  src/pages/project/members/index.ts
  src/pages/setting/role/role.hooks.ts
Labels: Refactor

#50 Refactor: 수정페이지 타입
  src/pages/project/edit/edit.types.ts
Labels: Refactor

#54 Feat : notification
  .eslintrc.json
  public/locales/en/notice.json
  public/locales/jp/notice.json
  public/locales/ko/notice.json
  src/assets/icons/bell.svg
  src/assets/icons/delete.svg
  src/assets/icons/index.ts
  src/components/Commons/Notifications/Notifications.tsx
  src/components/Commons/Notifications/index.ts
  src/components/Commons/index.ts
  src/components/Shared/LogoHeader/LogoHeader.styles.ts
  src/components/Shared/LogoHeader/LogoHeader.tsx
  src/components/Shared/Navbar/Navbar.tsx
  src/components/Shared/TitleHeader/TitleHeader.styles.ts
  src/components/Shared/TitleHeader/TitleHeader.tsx
  src/pages/_app.page.tsx
  src/pages/chat/components/InviteProjectCard/InviteProjectCard.hooks.tsx
  src/pages/chat/request/components/Member/Member.hooks.ts
  src/pages/chat/request/components/Owner/Owner.hooks.ts
  src/pages/chat/room/components/Owner/Invite/Invite.hooks.ts
  src/pages/home/index.page.tsx
  src/pages/like/components/Member/LikeMemberCard/LikeMemberCard.hooks.ts
  src/pages/like/components/Owner/LikeOwnerCard/LikeOwnerCard.hooks.ts
  src/pages/notice/components/NoticeList/NoticeList.hooks.ts
  src/pages/notice/components/NoticeList/NoticeList.styles.ts
  src/pages/notice/components/NoticeList/NoticeList.tsx
  src/pages/notice/components/NoticeList/index.ts
  src/pages/notice/components/index.ts
  src/pages/notice/index.page.tsx
  src/states/server/notice/apis.ts
  src/states/server/notice/index.ts
  src/states/server/notice/keys.ts
  src/states/server/notice/mutations.ts
  src/states/server/notice/queries.ts
  src/states/server/notice/types.ts
  src/types/database.ts
Labels: Feat

#55 Feat : notification
  package-lock.json
  package.json
  src/components/Commons/Menu/Menu.tsx
  src/components/Commons/Notifications/Notifications.tsx
  src/components/Commons/Notifications/index.ts
  src/components/Commons/index.ts
  src/components/Shared/LogoHeader/LogoHeader.tsx
  src/components/Shared/Navbar/Navbar.tsx
  src/pages/_app.page.tsx
  src/pages/like/components/Member/LikeMemberCard/LikeMemberCard.hooks.ts
  src/pages/notice/components/NoticeList/NoticeList.hooks.ts
  src/pages/notice/components/NoticeList/NoticeList.tsx
  src/states/server/firebase/config.ts
Labels: Feat

#57 Fix: 피드백 반영
  package-lock.json
  src/components/Commons/Modal/BottomSheetModal/BottomSheetModal.styles.ts
  src/components/Commons/Textarea/Textarea.styles.ts
  src/constants/regex.ts
  src/pages/boarding/index.page.tsx
  src/pages/chat/room/components/ChatHeaderMore/ChatHeaderMore.tsx
  src/pages/chat/room/components/Owner/Invite/Invite.tsx
  src/pages/profile/edit/edit.hooks.ts
  src/pages/project/create/index.page.tsx
  src/pages/project/edit/index.page.tsx
  src/pages/setting/index.page.tsx
  src/pages/setting/setting.styles.ts
  src/pages/welcome/components/Name/Name.hooks.ts
  src/pages/welcome/index.page.tsx
Labels: Fix

#59 Feat : notification
  package-lock.json
  package.json
  src/pages/_app.page.tsx
Labels: Refactor

#61 Refactor : 헤더 아이콘 간격 수정
  src/components/Shared/LogoHeader/LogoHeader.styles.ts
  src/pages/profile/profile.styles.ts
Labels: Refactor

#65 Design: 바텀 모달 그라데이션 수정
  src/components/Commons/Modal/BottomSheetModal/BottomSheetModal.styles.ts
  src/components/Commons/Modal/BottomSheetModal/BottomSheetModal.tsx
  src/components/Commons/ProfileDetail/ProfileDetail.styles.ts
  src/components/Commons/ProfileDetail/ProfileDetail.tsx
  src/components/Commons/ProjectDetail/ProjectDetail.styles.ts
Labels: Style

#71 Refactor : unused import 제거, 사용하지않는 세팅 제거
  next.config.js
  src/pages/profile/components/Member/Member.tsx
Labels: Refactor

#79 Docs: 리드미 수정
  README.md
Labels: Docs
