Repository jeonhaekang/teamver, pull requests merged in 2023-08, with the labels that each got.

#1 Feat : 공통 컴포넌트 생성
  next.config.js
  src/assets/icons/arrowBack.svg
  src/assets/icons/index.ts
  src/components/Commons/Avatar/Avatar.constants.ts
  src/components/Commons/Avatar/Avatar.styles.ts
  src/components/Commons/Avatar/Avatar.tsx
  src/components/Commons/Avatar/Avatar.types.ts
  src/components/Commons/Avatar/index.ts
  src/components/Commons/Buttons/PreviousButton/PreviousButton.tsx
  src/components/Commons/Buttons/PreviousButton/PreviousButton.types.ts
  src/components/Commons/Buttons/PreviousButton/index.ts
  src/components/Commons/Buttons/index.ts
  src/components/Commons/Chips/Chip/Chip.styles.ts
  src/components/Commons/Chips/Chip/Chip.tsx
  src/components/Commons/Chips/Chip/Chip.types.ts
  src/components/Commons/Chips/Chip/index.ts
  src/components/Commons/Chips/OptionChip/OptionChip.styles.ts
  src/components/Commons/Chips/OptionChip/OptionChip.tsx
  src/components/Commons/Chips/OptionChip/OptionChip.types.ts
  src/components/Commons/Chips/OptionChip/index.ts
  src/components/Commons/Chips/index.ts
  src/components/Commons/Dialogs/Dialogs.styles.ts
  src/components/Commons/Dialogs/Toast/Toast.styles.ts
  src/components/Commons/ImageUploader/ImageUploader.constants.ts
  src/components/Commons/ImageUploader/ImageUploader.hooks.ts
  src/components/Commons/ImageUploader/ImageUploader.styles.ts
  src/components/Commons/ImageUploader/ImageUploader.tsx
  src/components/Commons/ImageUploader/ImageUploader.types.ts
  src/components/Commons/ImageUploader/index.ts
  src/components/Commons/Modal/Modal.styles.ts
  src/components/Commons/Modal/Modal.tsx
  src/components/Commons/Modal/Modal.types.ts
  src/components/Commons/Textarea/Textarea.styles.ts
  src/components/Commons/Textarea/Textarea.tsx
  src/components/Commons/Textarea/Textarea.types.ts
  src/components/Commons/Textarea/index.ts
  src/components/Commons/index.ts
  src/pages/_app.page.tsx
  src/pages/_app.styles.ts
  src/pages/index.page.tsx
Labels: Feat, Design

#3 Fix : constants호출 및 다국어 설정 변경
  public/locales/en/common.json
  public/locales/en/welcome.json
  public/locales/jp/common.json
  public/locales/jp/welcome.json
  public/locales/ko/common.json
  public/locales/ko/welcome.json
  src/i18n/download.js
  src/i18n/upload.js
  src/states/server/constant/apis.ts
  src/states/server/constant/index.ts
  src/states/server/constant/keys.ts
  src/states/server/constant/queries.ts
  src/states/server/constant/types.ts
Labels: Feat, Fix

#6 Feat : 프로젝트 멤버 리스트 페이지
  src/pages/project/[projectId]/index.page.tsx
  src/pages/project/[projectId]/projectmembers.hooks.ts
  src/pages/project/[projectId]/projectmembers.styles.ts
  src/states/server/project/apis.ts
  src/states/server/project/keys.ts
  src/states/server/project/queries.ts
Labels: Feat, Style

#8 Feat : project apis
  src/states/server/project/apis.ts
  src/states/server/project/constants.ts
  src/states/server/project/index.ts
  src/states/server/project/keys.ts
  src/states/server/project/mutations.ts
  src/states/server/project/queries.ts
  src/states/server/project/types.ts
Labels: Feat

#11 Feat : 최초 프로필 정보 입력 프로세스 생성
  src/constants/routes.ts
  src/pages/index.page.tsx
  src/pages/member/index.page.tsx
  src/pages/owner/index.page.tsx
  src/pages/welcome/index.page.tsx
  src/pages/welcome/welcome.constants.ts
  src/pages/welcome/welcome.hooks.ts
  src/pages/welcome/welcome.types.ts
  src/states/server/profile/types.ts
Labels: Feat

#12 Fix : supabase table 수정에 따른 project api와 types 수정
  src/pages/member/index.page.tsx
  src/states/server/project/apis.ts
  src/states/server/project/constants.ts
  src/states/server/project/queries.ts
  src/states/server/project/types.ts
Labels: Fix

#13 Fix : 프로젝트 데이터 fetch시 owner의 profile도 불러오도록 수정
  src/pages/member/index.page.tsx
  src/states/server/project/constants.ts
  src/states/server/project/types.ts
Labels: Fix

#15 Feat: 내 채팅목록과 채팅방 구현
  src/components/ChatRoomOut/ChatRoomOut.constants.ts
  src/components/ChatRoomOut/ChatRoomOut.hooks.ts
  src/components/ChatRoomOut/ChatRoomOut.styles.ts
  src/components/ChatRoomOut/ChatRoomOut.tsx
  src/components/ChatRoomOut/index.ts
  src/components/Commons/Dialogs/Alert/Alert.types.ts
  src/components/Commons/Dialogs/Confirm/Confirm.tsx
  src/components/Commons/Dialogs/Dialogs.styles.ts
  src/components/ProjectInvite/ProjectInvite.hooks.ts
  src/components/ProjectInvite/ProjectInvite.styles.ts
  src/components/ProjectInvite/ProjectInvite.tsx
  src/components/ProjectInvite/index.ts
  src/constants/routes.ts
  src/pages/owner/chat/[roomId]/index.page.tsx
  src/pages/owner/chat/[roomId]/room.constants.ts
  src/pages/owner/chat/[roomId]/room.hooks.ts
  src/pages/owner/chat/[roomId]/room.styles.ts
  src/pages/owner/chat/chat.hooks.ts
  src/pages/owner/chat/chat.styles.ts
  src/pages/owner/chat/index.page.tsx
  src/pages/owner/chat/request/index.page.tsx
  src/states/server/chat/apis.ts
  src/states/server/chat/mutations.ts
  src/states/server/chat/queries.ts
  src/states/server/project/constants.ts
  src/styles/theme/colors.ts
Labels: Feat

#17 Feat : my page & 프로필 수정 기능 구현
  src/components/MyPage/ProjectCard/ProjectCard.styles.ts
  src/components/MyPage/ProjectCard/ProjectCard.tsx
  src/components/MyPage/ProjectCard/ProjectCard.types.ts
  src/components/MyPage/ProjectCard/index.ts
  src/components/MyPage/index.ts
  src/pages/mypage/index.page.tsx
  src/pages/mypage/mypage.hooks.ts
  src/pages/mypage/mypage.styles.ts
  src/pages/mypage/mypage.types.ts
  src/pages/mypage/profile/edit/edit.hooks.ts
  src/pages/mypage/profile/edit/edit.styles.ts
  src/pages/mypage/profile/edit/edit.types.ts
  src/pages/mypage/profile/edit/index.page.tsx
Labels: Feat, Refactor

#20 Feat:project member
  src/components/Profile/ProjectCard/ProjectCard.tsx
  src/components/ProjectMembers/Member/Member.constant.ts
  src/components/ProjectMembers/Member/Member.hooks.tsx
  src/components/ProjectMembers/Member/Member.tsx
  src/components/ProjectMembers/Member/index.ts
  src/components/ProjectMembers/Owner/Owner.constants.ts
  src/components/ProjectMembers/Owner/Owner.hooks.tsx
  src/components/ProjectMembers/Owner/Owner.tsx
  src/components/ProjectMembers/Owner/index.ts
  src/components/ProjectMembers/ProjectMembers.styles.ts
  src/components/ProjectMembers/ProjectMembers.types.ts
  src/components/ProjectMembers/index.ts
  src/pages/project/members/[projectId]/index.page.tsx
Labels: Feat

#22 Feat : 찜 목록에서 채팅 요청 기능
  src/components/Like/Like.styles.ts
  src/components/Like/LikeCardMember/LikeCardMember.hooks.ts
  src/components/Like/LikeCardMember/LikeCardMember.tsx
  src/components/Like/LikeCardMember/LikeCardMember.types.ts
  src/components/Like/LikeCardMember/index.ts
  src/components/Like/LikeCardOwner/LikeCardOwner.hooks.ts
  src/components/Like/LikeCardOwner/LikeCardOwner.tsx
  src/components/Like/LikeCardOwner/LikeCardOwner.types.ts
  src/components/Like/LikeCardOwner/index.ts
  src/components/Like/Member/Member.hooks.ts
  src/components/Like/Member/Member.tsx
  src/components/Like/Member/index.ts
  src/components/Like/Owner/Owner.hooks.ts
  src/components/Like/Owner/Owner.tsx
  src/components/Like/Owner/index.ts
  src/components/Like/index.ts
  src/pages/like/index.page.tsx
  src/pages/project/members/[projectId]/index.page.tsx
  src/states/server/chat/apis.ts
  src/states/server/chat/keys.ts
  src/states/server/chat/mutations.ts
  src/states/server/chat/queries.ts
  src/states/server/chat/types.ts
  src/states/server/profile/apis.ts
  src/states/server/profile/keys.ts
  src/states/server/profile/mutations.ts
  src/states/server/profile/queries.ts
  src/states/server/project/apis.ts
  src/states/server/project/keys.ts
  src/states/server/project/mutations.ts
  src/states/server/project/queries.ts
Labels: Feat
